name: grad
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.1.1
  font_awesome_flutter: ^8.4.0
  google_sign_in: ^5.0.3
  curved_navigation_bar: ^0.3.7
  firebase_auth: ^1.2.0
  camera: ^0.8.1+3
  percent_indicator: ^3.0.1
  native_video_view:
  dio: ^4.0.0
  image_gallery_saver: ^1.6.9
  permission_handler: ^8.1.2
  path_provider: ^1.6.0
  url_launcher: ^6.0.9
  firebase_core: ^1.5.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Oswald
      fonts:
        - asset: images/Oswald-Bold.ttf
          weight: 700
    - family: Cardo
      fonts:
        - asset: images/Cardo-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: images/Nunito-Bold.ttf
          weight: 700